<!doctype html>
<html lang="th">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Surprise for You 💖</title>
  <style>
    :root{--bg:#0f172a;--card:#0b1220;--accent:#ef476f;--muted:#94a3b8}
    body{margin:0;background:linear-gradient(180deg,#071023 0%, #0b1330 100%);color:#e6eef8;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px;font-family:'Noto Sans Thai',sans-serif}
    .card{background:rgba(255,255,255,0.05);border-radius:14px;padding:20px;max-width:900px;width:100%;box-shadow:0 8px 30px rgba(2,6,23,0.6)}
    header{display:flex;align-items:center;justify-content:space-between;gap:10px}
    h1{margin:0;font-size:1.6rem}
    .subtitle{color:var(--muted);font-size:0.95rem}
    .btn{background:linear-gradient(90deg,var(--accent),#ff8fab);border:none;color:white;padding:10px 14px;border-radius:10px;cursor:pointer}
    .editable{outline:2px dashed transparent;padding:4px;border-radius:6px}
    .editable[contenteditable="true"]{outline-color:rgba(239,71,111,0.18)}
    .grid{display:grid;grid-template-columns:1fr 300px;gap:18px;margin-top:18px}
    .right{background:rgba(255,255,255,0.02);padding:12px;border-radius:10px}
    @media(max-width:880px){.grid{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <div class="card">
    <header>
      <div>
        <h1 id="title" class="editable">เซอร์ไพรส์สำหรับคนพิเศษ</h1>
        <div class="subtitle" id="subtitle">ยินดีต้อนรับ 💕</div>
      </div>
      <div style="display:flex;gap:8px">
        <button class="btn" id="playBtn">▶ เล่นเพลง</button>
      </div>
    </header>

    <div class="grid">
      <div>
        <p>ถึง <span id="toName" class="editable">ที่รักของฉัน</span>,</p>
        <p id="mainMessage" class="editable">อยากให้รู้ว่าฉันดีใจที่มีเธออยู่ในชีวิต 💖</p>
        <div id="resultArea" style="margin-top:20px"></div>
      </div>
      <aside class="right">
        <h3>เมนูคำขอ</h3>
        <button class="btn" onclick="showResult('ส่งรอยยิ้มกลับมาให้หน่อย 😊')">ขอรอยยิ้ม</button>
        <button class="btn" onclick="showResult('บอกว่า คิดถึง ฉันหน่อย 💬')">ขอคำหวาน</button>
        <button class="btn" onclick="showResult('กดเล่นเพลงประจำของเรา 🎶')">ขอเพลง</button>
      </aside>
    </div>
  </div>

  <audio id="bgAudio" loop preload="auto">
    <source src="song.mp3" type="audio/mpeg">
  </audio>

  <script>
    const bgAudio=document.getElementById('bgAudio');
    const playBtn=document.getElementById('playBtn');
    const urlParams=new URLSearchParams(window.location.search);
    const mode=urlParams.get('mode');

    // toggle edit mode based on URL
    const editables=document.querySelectorAll('.editable');
    if(mode==='edit'){
      editables.forEach(e=>e.contentEditable=true);
      alert('โหมดแก้ไขเปิดอยู่ ✅\nอย่าลืมบันทึกไฟล์หลังแก้เสร็จ');
    } else {
      editables.forEach(e=>e.contentEditable=false);
    }

    // play music
    playBtn.addEventListener('click',()=>{
      if(bgAudio.paused){bgAudio.play();playBtn.textContent='⏸ หยุดเพลง'}
      else{bgAudio.pause();playBtn.textContent='▶ เล่นเพลง'}
    });

    // show message result
    function showResult(text){
      document.getElementById('resultArea').innerHTML='<div style="margin-top:10px;padding:12px;background:rgba(255,255,255,0.05);border-radius:10px">'+text+'</div>';
    }
  </script>
</body>
</html>
